<Project Sdk="Godot.NET.Sdk/4.2.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <!-- Use NativeAOT. -->
<!--    <PublishAOT>true</PublishAOT>-->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="addons\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="addons\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="addons\Core.Godot\Core.Godot.csproj" />
    <ProjectReference Include="addons\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Root the assemblies to avoid trimming. -->
<!--    <TrimmerRootAssembly Include="GodotSharp" />-->
<!--    <TrimmerRootAssembly Include="$(TargetName)" />-->
  </ItemGroup>
</Project>