<Project Sdk="Godot.NET.Sdk/4.5.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Flecs.NET.Release" Version="4.0.3" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Libraries\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Libraries\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Libraries\Core.Godot\Core.Godot.csproj" />
    <ProjectReference Include="Libraries\Core\Core.csproj" />
  </ItemGroup>
</Project>